### ISSUE TITLE
No module named 'qtribu-0'

### ISSUE THREAD

**Issue by igeofr** [geotribu/qtribu#86]
### What is the bug or the crash?

Impossible de charger l'extension 'qtribu-0.15.0-beta1/qtribu' 

ModuleNotFoundError: No module named 'qtribu-0' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qtribu-0'

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.26.2-Buenos Aires Buenos Aires, feec3d3b12f 

### Steps to reproduce the issue

1. Installer depuis un zip
2. Installer le plugin

### Versions

Version de QGIS | 3.26.2-Buenos Aires
Windows 10 Pro

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the official roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Guts** [comment]
Je ne reproduis pas :

- ni en utilisant un profil à vide avec une nouvelle installation
- ni en mettant à jour dans un profil où le plugin était déjà installé

Peux-tu me donner l'entièreté des versions stp ? notamment les versions de Qt. ça plante aussi en redémarrant QGIS et en réactivant l'extension ?

**Comment by igeofr** [comment]
J'ai relancé QGIS et il m'a proposé dans les MAJ. Installation réussie ✔

Par contre avec une installation manuelle à partir du zip, j'ai toujours le message d'erreur.
Version de QGIS | 3.26.2-Buenos Aires | Révision du code | feec3d3b12f
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.5.1
Version de Proj | 9.0.1
Version de la base de données du registre EPSG | v10.064 (2022-05-19)
Version de GEOS | 3.10.3-CAPI-1.16.1
Version de SQLite | 3.38.1
Version de PDAL | 2.4.2
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009

**Comment by igeofr** [comment]
![Capture](https://user-images.githubusercontent.com/7761073/186115974-7a396b23-06d2-4922-ba01-9a9baebf8db3.PNG)
